server:
  port: 8080

spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/shenshuaihu/SpringCloud_Sell-config.git
          basedir: /file/docker/log/demo/config/dir
          username: shen_shuaihu@163.com
          password: shenshuihu0
  rabbitmq:
    host: 212.64.11.85
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: "*"      # 暴露所有接口
      cors:
        allowed-origins: "*"
        allowed-methods: "*"

eureka:
  client:
    service-url:
      defaultZone: http://sell-eureka1:8761/eureka,http://sell-eureka2:8762/eureka
  instance:
    prefer-ip-address: true
